name: C/C++ CI

on:
  push:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-18.04
          - ubuntu-16.04
          - macos-latest
          - macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
